### ISSUE TITLE
Services uuid

### ISSUE THREAD

**Issue by Matioupi** [rgrunbla/Stop_Covid_Detector_3000#1]
Official services uuid are available here : https://app.stopcovid.gouv.fr/json/version-22/config.json

**Comment by rgrunbla** [comment]
Thanks. You want to do a pull request? It seems I'll have to rework a bit of code to adapt to the 1.0 that have been pushed.

The 0xfd64 uuid has not been put online on https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-members/

I don't have the application (yet), but I guess the ble.characteristicUUID is the identifier of the serviceData.

Are we sure these UUIDs won't change (again) til the official release?

**Comment by rgrunbla** [comment]
I just pushed an updated version.
